title: Michael Enger
description: I am a professional. This is my website.
image: happybass.png
root_url: https://michaelenger.com

data:
  experience:
    - title: Senior Software Engineer
      employer: Sony Music PDE
      link: https://www.sonymusic.com/
      date: Apr 2019 – Present
      description: Sony Music Product Design & Engineering provides software to facilitate music distribution services for Sony Music subsidiaries. I’ve worked on a series of projects within their distribution portal related to calculating royalties for artists. The projects consists of Python micro-services running in AWS, React-based frontend applications, connected using a federated GraphQL network. I also designed and implemented a data processing pipeline running in a set of AWS Lambda serverless functions that connect to a Snowflake data warehouse table to generate reports.
      tech:
        Python: true
        TypeScript: true
        MySQL: true
    - title: Desktop Engineer
      employer: TIDAL
      link: https://tidal.com/
      date: Dec 2016 – Mar 2019
      description: TIDAL is a music streaming service, known for their curated content and high quality audio playback. My position was to work on the desktop application which was built on Electron and includes a C++ audio playback engine that provides playback via Core Audio on macOS and WASAPI on Windows. The audio engine provides decoding of all the supported audio formats (FLAC and MP3), gapless playback, and exclusive control of USB audio devices.
      tech:
        C++: true
        TypeScript: true
        Python: true
    - title: Web Developer
      employer: Dekode
      link: https://dekode.no/
      date: Dec 2014 – Oct 2015
      description: Dekode is a WordPress development agency working with local clients and on WordPress VIP sites together with Automaticc. I mainly worked on new and existing WordPress sites, building and maintaining their custom themes and plugins.
      tech:
        PHP: true
        JavaScript: true
        MySQL: true
    - title: Backend Developer
      employer: Fronter AS
      date: Apr 2014 – Nov 2014
      description: Fronter is a company which provides a platform for schools and universities, which includes lesson plans, assignment hand-in, and social features. I was on a small team which was developing a lesson planner in Node.js using ElasticSearch as a data store, all hosted on scalable AWS infrastructure.
      tech:
        JavaScript: true
        ElasticSearch: true
    - title: Web Developer
      employer: Nodes Agency
      date: Apr 2012 – Jun 2013
      description: Nodes Agency is a consultancy building promotional projects for mobile and web. Work consisted mostly of backend work on smaller apps for customers, alongside some work on FFMpeg-based video processing pipelines and mobile experiences.
      tech:
        PHP: true
        JavaScript: true
        MySQL: true
        Objective-C: true
    - title: Web Developer
      employer: 07 Web
      date: Aug 2010 - Jan 2012
      description: 07 Web is a web consultancy specialising in online magazines. I worked on pages created using the eZ Publish platform.
      tech:
        PHP: true
        JavaScript: true
        MySQL: true
  education:
    - degree: Computer Games Technology MSc
      school: City University London
      year: 2016
      location: London, England
    - degree: Computer Science Bachelor
      school: Universitet i Oslo
      location: Oslo, Norway
      year: 2009
  projects:
    - title: Galleri
      link: https://github.com/michaelenger/Galleri
      description: Basic image gallery for macOS, with support for animated GIFs.
      tech:
        Swift: asd
    - title: brage
      link: https://github.com/michaelenger/brage
      description: Command-line tool for generating static websites based on Markdown and Mustache templates. Was used to build this website and several others that I manage.
      tech:
        Go: true
    - title: gifff
      link: https://github.com/michaelenger/gifff
      description: Tiny command-line tool used for fetching gif images based on a search term. Features wrapping the resulting URL in some Markdown, and keeping a cache of already-seen images.
      tech:
        Rust: true
  music:
    - year: 2022
      songs:
        - artist: Beyond The Barricade
          title: Weightless (stripped)
          credits: Lyrics
        - artist: Hilltops Are For Dreamers
          title: Silence
          credits: Vocals
        - artist: Hilltops Are For Dreamers
          title: Severe Serenity
          credits: Vocals
        - artist: Hilltops Are For Dreamers
          title: Healing After the Fall
          credits: Vocals
        - artist: Hilltops Are For Dreamers
          title: The Tide
          credits: Vocals
        - artist: Hilltops Are For Dreamers
          title: Turn Into Oblivion
          credits: Vocals
        - artist: Hilltops Are For Dreamers
          title: The Sirens Woe
          credits: Vocals
        - artist: Hilltops Are For Dreamers
          title: Revival
          credits: Vocals
        - artist: Hilltops Are For Dreamers
          title: Unsoiled Soul
          credits: Vocals
        - artist: Yeah, Nevermind
          title: Mona Avdahlia—Vampire
          credits: Lyrics, Composition, Vocals, Bass
        - artist: Yeah, Nevermind
          title: The One Who Got Away
          credits: Lyrics, Composition, Vocals, Bass
        - artist: Yeah, Nevermind
          title: Hollow
          credits: Lyrics, Composition, Vocals, Acoustic Guitar
        - artist: Young Fatigue
          title: Top 10 Anime Betrayals
          credits: Bass
        - artist: Young Fatigue
          title: I Want (Everything)
          credits: Bass
        - artist: Young Fatigue
          title: love/them
          credits: Bass, Vocals
    - year: 2021
      songs:
        - artist: Beyond The Barricade
          title: Wither
          credits: Lyrics, Composition, Vocals, Acoustic Guitar
        - artist: Beyond The Barricade
          title: Bring Me To Life
          credits: Vocals
        - artist: Beyond The Barricade
          title: Trapped
          credits: Lyrics, Composition, Vocals
        - artist: Beyond The Barricade
          title: Set It Free
          credits: Lyrics, Composition, Vocals
        - artist: Beyond The Barricade
          title: Forgotten
          credits: Lyrics, Composition, Vocals
        - artist: Beyond The Barricade
          title: Marching On
          credits: Lyrics, Composition, Vocals
        - artist: Beyond The Barricade
          title: Born In The Rain
          credits: Lyrics, Composition, Vocals
        - artist: Beyond The Barricade
          title: Dreamer
          credits: Lyrics, Composition, Vocals
        - artist: Beyond The Barricade
          title: Honesty
          credits: Lyrics, Composition, Vocals
        - artist: Beyond The Barricade
          title: Circles
          credits: Lyrics, Composition, Vocals
        - artist: Beyond The Barricade
          title: Falling
          credits: Lyrics, Composition, Vocals
        - artist: Beyond The Barricade
          title: Weightless
          credits: Lyrics, Composition, Vocals
        - artist: Young Fatigue
          title: Am I Pretty Now?
          credits: Bass
    - year: 2020
      songs:
        - artist: Beyond The Barricade
          title: Forest
          credits: Lyrics, Composition, Vocals
        - artist: Beyond The Barricade
          title: Reflections
          credits: Lyrics, Composition, Vocals
        - artist: Beyond The Barricade
          title: S I C K N E S S
          credits: Lyrics, Composition, Vocals
        - artist: Hilltops Are For Dreamers
          title: The Tide
          credits: Vocals
        - artist: Hilltops Are For Dreamers
          title: All We Need
          credits: Vocals
        - artist: Young Fatigue
          title: Dislocation
          credits: Bass
    - year: 2018
      songs:
        - artist: Beyond The Barricade
          title: Splitting the Silence
          credits: Lyrics, Composition, Vocals
        - artist: Beyond The Barricade
          title: The Grey
          credits: Lyrics, Composition, Vocals
        - artist: Beyond The Barricade
          title: A Letter of Hopelessness
          credits: Lyrics, Composition, Vocals
        - artist: Beyond The Barricade
          title: Shattering
          credits: Lyrics, Composition, Vocals
        - artist: Beyond The Barricade
          title: The River Runs Deep
          credits: Lyrics, Composition, Vocals
    - year: 2016
      songs:
        - artist: Firetop Mountain
          title: Failed to Start
          credits: Lyrics
        - artist: Firetop Mountain
          title: Complications
          credits: Lyrics
        - artist: Firetop Mountain
          title: Connected
          credits: Lyrics
        - artist: Firetop Mountain
          title: Derelict Me
          credits: Lyrics
    - year: 2013
      songs:
        - artist: Firetop Mountain
          title: All the Best Ideas
          credits: Bass
        - artist: Firetop Mountain
          title: Fearless
          credits: Bass
        - artist: Firetop Mountain
          title: Paper Planes
          credits: Bass
        - artist: Firetop Mountain
          title: Everyone Loves a Witch Hunt
          credits: Bass
        - artist: Firetop Mountain
          title: Spiders
          credits: Bass
