title: Michael Enger
description: I am a professional. This is my website.
image: happybass.png
rootUrl: https://michaelenger.com

data:
  experience:
    - title: Senior Software Engineer
      employer: The Orchard
      date: Apr 2019 – Present
      description: "[The Orchard](https://www.theorchard.com/) provides music and video distribution services for music labels and artists. I’ve worked on a series of projects within their distribution portal related to calculating royalties for artists. The projects consists of Flask micro-services running in AWS, React-based frontend applications, and using GraphQL to communicate between them. The actual calculations are done on a separate ETL process running in AWS Lambdas that connects to a Snowflake table and generates XLS reports and PDF documents."
      tech:
        - Python
        - TypeScript
        - MySQL
    - title: Desktop Engineer
      employer: TIDAL
      date: Dec 2016 – Mar 2019
      description: "[TIDAL](https://tidal.com/) is a music streaming service, known for their curated content and high quality audio playback. My position was to work on the desktop application which was built on Electron and includes a C++ audio playback engine that provides playback via Core Audio on macOS and WASAPI on Windows. The audio engine provides decoding of all the supported audio formats (FLAC and MP3), gapless playback, and exclusive control of USB audio devices."
      tech:
        - C++
        - TypeScript
        - Python
    - title: Web Developer
      employer: Dekode
      date: Dec 2014 – Oct 2015
      description: "[Dekode](https://dekode.no/) is a WordPress development agency working with local clients and on WordPress VIP sites together with Automaticc. I mainly worked on new and existing WordPress sites, building and maintaining their custom themes and plugins."
      tech:
        - PHP
        - JavaScript
        - MySQL
    - title: Backend Developer
      employer: Fronter AS
      date: Apr 2014 – Nov 2014
      description: Fronter is a company which provides a platform for schools and universities, which includes lesson plans, assignment hand-in, and social features. I was on a small team which was developing a lesson planner in Node.js using ElasticSearch as a data store, all hosted on scalable AWS infrastructure.
      tech:
        - JavaScript
        - ElasticSearch
    - title: Web Developer
      employer: Nodes Agency
      date: Apr 2012 – Jun 2013
      description: Nodes Agency is a consultancy building promotional projects for mobile and web. Work consisted mostly of backend work on smaller apps for customers, alongside some work on FFMpeg-based video processing pipelines and mobile experiences.
      tech:
        - PHP
        - JavaScript
        - MySQL
        - Objective-C
    - title: Web Developer
      employer: 07 Web
      date: Aug 2010 - Jan 2012
      description: 07 Web is a web consultancy specialising in online magazines. I worked on pages created using the eZ Publish platform.
      tech:
        - PHP
        - JavaScript
        - MySQL
  education:
    - degree: Computer Games Technology MSc
      school: City University London
      year: 2016
      location: London, England
    - degree: Computer Science Bachelor
      school: Universitet i Oslo
      location: Oslo, Norway
      year: 2009
  projects:
    - title: ポテート
      link: https://github.com/michaelenger/poteto
      description: An implementation of the single-page RPG "Potato" for the WASM-4 fantasy console.
      tech:
        - Rust
    - title: brage
      link: https://github.com/michaelenger/brage
      description: Command-line tool for generating static websites based on Markdown and Go text templates. Was used to build this website and several others that I manage.
      tech:
        - Go
    - title: gifff
      link: https://github.com/michaelenger/gifff
      description: Tiny command-line tool used for fetching gif images based on a search term. Features wrapping the resulting URL in some Markdown, and keeping a cache of already-seen images.
      tech:
        - Rust
