title: Michael Enger
description: I am a professional. This is my website.
image: bisniss.jpg
rootUrl: https://michaelenger.com

data:
  links:
    - title: GitHub
      url: https://github.com/michaelenger/
    - title: Instagram
      url: https://www.instagram.com/michaelenger/
    - title: LinkedIn
      url: https://www.linkedin.com/in/michael-enger-802094110
    - title: Twitter
      url: https://twitter.com/michaelenger
    - title: YouTube
      url: https://www.youtube.com/playlist?list=PLEUcBq9izIjXH3zPKSqy3lpvSanGS6ole
  experience:
    - title: Senior Software Engineer
      employer: The Orchard
      date: Apr 2019 – Present
      description: The Orchard provides music and video distribution services for music labels and artists. I’ve worked on a series of projects within their distribution portal related to calculating royalties for artists. The projects consists of Python micro-services running in AWS, React-based frontend applications, and using GraphQL to communicate between them. The actual calculations are done on a separate ETL process running in an AWS Lambda that connects to a Snowflake table and generates XLS reports and PDF documents.
      tech:
        - Python
        - Flask
        - SQL
        - SqlAlchemy
        - TypeScript
        - GraphQL
        - AWS
        - Docker
        - Terraform
    - title: Software Engineer
      employer: TIDAL
      date: Dec 2016 – Mar 2019
      description: TIDAL is a music streaming service, known for their curated content and high quality audio playback. My position was to work on the desktop application which was built on Electron and includes a C++ audio playback engine that provides playback via Core Audio on macOS and WASAPI on Windows. The audio engine provides decoding of all the supported audio formats, gapless playback, and exclusive control of USB audio devices.
      tech:
        - C++
        - FLAC
        - TypeScript
        - Python
        - Electron
    - title: Web Developer
      employer: Dekode
      date: Dec 2014 – Oct 2015
      description: Dekode is a WordPress development agency working with local clients and on WordPress VIP sites together with Automaticc. I mainly worked on new and existing WordPress sites, building and maintaining their custom themes and plugins.
      tech:
        - PHP
        - JavaScript
        - MySQL
        - WordPress
    - title: Backend Developer
      employer: Fronter AS
      date: Apr 2014 – Nov 2014
      description: Fronter is a company which provides a platform for schools and universities, which includes lesson plans, assignment hand-in, and social features. I was on a small team which was developing a lesson planner in Node.js using ElasticSearch as a data store, all hosted on scalable AWS infrastructure.
      tech:
        - JavaScript
        - Node.js
        - ElasticSearch
        - AWS
        - Ansible
        - Vagrant
        - Jenkins
    - title: Web Developer
      employer: Nodes Agency
      date: Apr 2012 – Jun 2013
      description: Nodes Agency is a consultancy building promotional projects for mobile and web. My work consisted of mostly backend work on smaller apps for customers, but with some work on video processing pipelines and mobile experiences.
      tech:
        - PHP
        - JavaScript
        - MySQL
        - Objective-C
        - FFmpeg
    - title: Web Developer
      employer: 07 Web
      date: Aug 2010 - Jan 2012
      description: 07 Web is a web consultancy specialising in online magazines. I worked on pages created using the eZ Publish platform.
      tech:
        - PHP
        - JavaScript
        - MySQL
        - eZ Publish
  education:
    - degree: Computer Games Technology MSc
      school: City University London
      year: 2016
      location: London, England
    - degree: Computer Science Bachelor
      school: Universitet i Oslo
      location: Oslo, Norway
      year: 2009
  projects:
    - title: swifter
      link: github.com/httpswift/swifter
      description: Tiny HTTP server engine built as a library for Swift projects. I joined the project last year and have been involved in the latest release doing bug fixes and approving merge requests.
      tech:
        - Swift
    - title: brage
      link: github.com/michaelenger/brage
      description: Command-line tool for generating static websites based on Markdown and Go text templates, built to help me easier create and manage websites for the various bands and artists I help promote.
      tech:
        - Go
    - title: gifff
      link: github.com/michaelenger/gifff
      description: Tiny command-line tool used for fetching gif images from gfycat.com. It can take any text as a search term and returns a URL to a random gif based on it, or one of the trending gifs from Gfycat’s front page. It also keeps track of what gifs you have already seen so that you avoid seeing the same one twice.
      tech:
        - Rust
