title: Michael Enger
description: I am a professional. This is my website.
image: bisniss.jpg
rootUrl: https://michaelenger.com

data:
  links:
    - title: Instagram
      url: https://www.instagram.com/michaelenger/
    - title: LinkedIn
      url: https://www.linkedin.com/in/michael-enger-802094110
    - title: Twitter
      url: https://twitter.com/michaelenger
    - title: YouTube
      url: https://www.youtube.com/playlist?list=PLEUcBq9izIjXH3zPKSqy3lpvSanGS6ole
